language: python
python:     # current default Python on Travis CI
  - "3.7"

branches:
  only: 
    - main

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - black app tests
  - isort app tests
  - python -m pylint app tests
  - python -m mypy app tests

script:
  - python -m pytest tests --cov

deploy:
  provider: gae
  keyfile: personal-website-318015-bf6cbd444844.json.enc
  project: personal-website-318015
  on: main