language: python
python:
- '3.7'
branches:
  only:
  - main
install:
- pip install -r requirements.txt
script:
- python -m pytest tests --cov
deploy:
  provider: gae
  keyfile: personal-website-318015-bf6cbd444844.json
  project: personal-website-318015
  on: main
before_install:
- openssl aes-256-cbc -K $encrypted_9a2b19b22e89_key -iv $encrypted_9a2b19b22e89_iv
  -in personal-website-318015-bf6cbd444844.json.enc -out personal-website-318015-bf6cbd444844.json
  -d
