runtime: nodejs22

handlers:
  # Serve static assets with cache
  - url: /assets
    static_dir: dist/website/browser/assets
    secure: always

  # Serve favicon
  - url: /favicon.ico
    static_files: dist/website/browser/favicon.ico
    upload: dist/website/browser/favicon.ico
    secure: always

  # Serve JS bundles
  - url: /(.*\.js)
    static_files: dist/website/browser/\1
    upload: dist/website/browser/.*\.js
    secure: always

  # Serve CSS bundles
  - url: /(.*\.css)
    static_files: dist/website/browser/\1
    upload: dist/website/browser/.*\.css
    secure: always

  # All other routes go to index.html (SPA routing)
  - url: /.*
    static_files: dist/website/browser/index.html
    upload: dist/website/browser/index.html
    secure: always
