steps:
  - name: 'node:22'
    entrypoint: 'npm'
    args: ['ci']

  - name: 'node:22'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

timeout: '1600s'
