steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Check import formatting
  - name: python
    entrypoint: python
    args: ["-m", "isort", "--check", "app", "gcp_util", "telegram_bot"]

  # Check formatting
  - name: python
    entrypoint: python
    args: ["-m", "black", "--check", "app", "gcp_util", "telegram_bot"]

  # Check formatting
  - name: python
    entrypoint: python
    args: ["-m", "pylint", "app", "gcp_util","telegram_bot"]

  # Run tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest"]
  
  # build and deploy the webapp
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]

timeout: "1600s"