steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Check import formatting
  - name: python
    entrypoint: python
    args: ["-m", "isort", "--check", "app", "bots"]

  # Check formatting
  - name: python
    entrypoint: python
    args: ["-m", "black", "--check", "app", "bots"]

  # Check formatting
  - name: python
    entrypoint: python
    args: ["-m", "pylint", "app", "bots"]

  # Run tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest"]
  

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"