steps:
  # Install universal-vendoring
  - name: python
    entrypoint: python
    args: ["-m", "pip", "install", "uv"]

  # Use uv to install vendored dependencies
  - name: python
    entrypoint: python
    args: ["-m", "uv", "install"]

  # Check import formatting
  - name: python
    entrypoint: python
    args: ["-m", "isort", "--check", "app", "gcp_util", "telegram_bot"]

  # Check formatting
  - name: python
    entrypoint: python
    args: ["-m", "black", "--check", "app", "gcp_util", "telegram_bot"]

  # Check linting
  - name: python
    entrypoint: python
    args: ["-m", "pylint", "app", "gcp_util", "telegram_bot"]

  # Run tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest"]

timeout: "1600s"
