steps:
  - name: python
    entrypoint: curl
    args: [
     "-LsSf https://astral.sh/uv/install.sh | sh"
    ]

  # Install dependencies
  - name: python
    entrypoint: uv
    args: ["sync"]

  # Check import formatting
  - name: python
    entrypoint: uv
    args: ["run", "isort", "--check", "app"]

  # Check formatting
  - name: python
    entrypoint: python
    args: ["-m", "black", "--check", "app"]

  # Check linting
  - name: python
    entrypoint: python
    args: ["-m", "pylint", "app"]

  # Run tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest"]

timeout: "1600s"
