steps:
  - name: python
    entrypoint: python
    args: [
      "-c", 
      "import subprocess; subprocess.run(['pip', 'install', 'uv']); subprocess.run(['python', '-m', 'uv', 'pip', 'install'])"
    ]

  # Check import formatting
  - name: python
    entrypoint: python
    args: ["-m", "isort", "--check", "app"]

  # Check formatting
  - name: python
    entrypoint: python
    args: ["-m", "black", "--check", "app"]

  # Check linting
  - name: python
    entrypoint: python
    args: ["-m", "pylint", "app"]

  # Run tests
  - name: python
    entrypoint: python
    args: ["-m", "pytest"]

timeout: "1600s"
